### PR TITLE
Add createA' and createA1'

### PR DESCRIPTION
**Pull request by Lysxia**
Similar to `createA`, for record types without requiring `Alternative`.

Pretty useful for this kind of boilerplate

    Constructor <$> arbitrary <*> arbitrary <*> arbitrary <*> arbitrary

### CODE REVIEW

**Comment by Lysxia** [comment]
Would this this be better placed under "Functions for records"?

**Comment by sjoerdvisscher** [comment]
Yes, could you move them? Thanks a lot for your interest in my package!

**Comment by Lysxia** [comment]
It is done.

This is a really cool package!

**Comment by sjoerdvisscher** [comment]
Thanks again!

**Pull request merged**
